### ISSUE TITLE
#13 Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by yashgosa** [tcet-opensource/resume-screener#31]
I noticed that this repo doesn't have contribution guidelines file.

**Comment by yashgosa** [comment]
@Hrishikesh332 @prathikshetty2002 I have created CONTRIBUTING.md if you want any changes then mention them below.

**Comment by prathikshetty2002** [comment]
@yashgosa we are not adding a contributing.md for now. As that has to be decided by open source management team the process of contributing isn't open to people from other than AI team . I'm closing this issue will reopen when we open contribution fr everyone
