### ISSUE TITLE
#18 Feat: Create linkedln analyser function

### ISSUE THREAD

**Issue by prathikshetty2002** [tcet-opensource/resume-screener#44]
Name the file linkedln_analyser.py

- [x] Import the user profile data from utils/linekdln_scrapper.py 
- [x] Do pre-processing on the linkedln user data and transform it
- [x] get the job profile description 
- [x] perform content-based analysis using cosine similarity on it
- [x] output matching score and grade 

Keep this model inside models/

**Comment by Ankkkyyyy** [comment]
Done, I've tested the changes locally and everything seems to be working fine.
 @prathikshetty2002

**Comment by prathikshetty2002** [comment]
Great work @Ankkkyyyy ! will close this for now
