### ISSUE TITLE
#20 Feat: Create Github analyser function

### ISSUE THREAD

**Issue by prathikshetty2002** [tcet-opensource/resume-screener#46]
Name the file github_analyser.py

- [x] Import the user profile data from utils/github_scrapper.py 
- [x] Do pre-processing on the github user data and transform it
- [x] get the job profile description 
- [x] perform content-based analysis using cosine similarity on it
- [x] output matching score and grade 

Keep this model inside models/

**Comment by prathikshetty2002** [comment]
@sanyamjain0315 This issue is assigned to you🚀

**Comment by prathikshetty2002** [comment]
@sanyamjain0315 can u link ur PR to this issue it would be easier to track that way as project will grow exponentially it will become hectic to reference past issues/PRs.

**Comment by sanyamjain0315** [comment]
Sure, here is the link to the PR:
https://github.com/tcet-opensource/resume-screener/pull/48
