### ISSUE TITLE
#22 [Feat] : User domain/profession recommendation

### ISSUE THREAD

**Issue by prathikshetty2002** [tcet-opensource/resume-screener#50]
Name the file identify_user_domain.py

- [x] Import the user profile data from utils/extract_resume_json.py 
- [x] Do pre-processing on the user data and transform it
- [x] get the job relevant skills description 
- [x] perform rule based mapping on skills and profession
- [x] output matching profession

Keep this model inside models/

**Comment by Hrishikesh332** [comment]
Necessary pre-processing steps to transform the user data, extract job relevant skills, and perform rule-based mapping on skills and profession.

**Comment by prathikshetty2002** [comment]
Closing this issue temporarily until further work is required!
