### ISSUE TITLE
#31 resume length

### ISSUE THREAD

**Issue by sanyamjain0315** [tcet-opensource/resume-screener#62]
* Make a file './utils/ats_functions.py' which has class 'Ats_Functions' and make the function under this class 
	- [x] Check for number of characters/words in resume
	- [x] Ensure that the number does not exceed a specific threshold
	- [x] Return weather resume is acceptable (character count)

**Comment by rrahulg** [comment]
- [x] checked the number of characters/words from ~~resume~~ the json file (temp.json)
- [x] ensured that the number doesnt exceed a specific threshold  
- [x] returned True if acceptable else returns False
